---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: install java on ubuntu nodes
    apt: 
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on redhat nodes
    ansible.builtin.dnf: 
       name: "{{myjavapackonredhat}}"
       state: present
    when: ansible_os_family =="RedHat"  